"""initial_schema

Revision ID: ee400488cb93
Revises: 
Create Date: 2026-08-03 13:30:41.724041

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee400488cb93'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('actor_id', sa.String(length=128), nullable=True),
    sa.Column('resource_type', sa.String(length=64), nullable=True),
    sa.Column('resource_id', sa.String(length=128), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_events_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_occurred_at'), ['occurred_at'], unique=False)

    op.create_table('benchmark_snapshots',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('questionnaire_version', sa.String(length=20), nullable=False),
    sa.Column('scoring_version', sa.String(length=20), nullable=False),
    sa.Column('cohort_version', sa.String(length=20), nullable=False),
    sa.Column('rebalancing_version', sa.String(length=20), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('primary_data_cutoff', sa.DateTime(), nullable=True),
    sa.Column('distributions_json', sa.JSON(), nullable=False),
    sa.Column('top_quartile_practices_json', sa.JSON(), nullable=False),
    sa.Column('rebalancing_weights_json', sa.JSON(), nullable=False),
    sa.Column('privacy_thresholds_json', sa.JSON(), nullable=False),
    sa.Column('methodology_notes', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('approved_by', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contact_store',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('response_id_hash', sa.String(length=64), nullable=False),
    sa.Column('encrypted_email', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('delivered', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('contact_store', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contact_store_response_id_hash'), ['response_id_hash'], unique=False)

    op.create_table('response_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('questionnaire_version', sa.String(length=20), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('received_at', sa.DateTime(), nullable=False),
    sa.Column('region_band', sa.String(length=32), nullable=True),
    sa.Column('dc_type_band', sa.String(length=32), nullable=True),
    sa.Column('capacity_band', sa.String(length=32), nullable=True),
    sa.Column('workload_band', sa.String(length=32), nullable=True),
    sa.Column('validation_status', sa.String(length=16), nullable=False),
    sa.Column('quality_score', sa.Float(), nullable=False),
    sa.Column('included_in_dataset', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key', name='uq_response_idempotency')
    )
    with op.batch_alter_table('response_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_response_sessions_idempotency_key'), ['idempotency_key'], unique=False)

    op.create_table('aggregate_metrics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('snapshot_id', sa.String(length=36), nullable=False),
    sa.Column('dimension', sa.String(length=64), nullable=False),
    sa.Column('cohort_id', sa.String(length=256), nullable=False),
    sa.Column('window_start', sa.DateTime(), nullable=False),
    sa.Column('window_end', sa.DateTime(), nullable=False),
    sa.Column('n_bruto', sa.Integer(), nullable=False),
    sa.Column('n_effective', sa.Integer(), nullable=False),
    sa.Column('method', sa.String(length=64), nullable=False),
    sa.Column('privacy_threshold', sa.Integer(), nullable=False),
    sa.Column('approval_status', sa.String(length=16), nullable=False),
    sa.Column('metrics_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['snapshot_id'], ['benchmark_snapshots.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('answers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('question_id', sa.String(length=64), nullable=False),
    sa.Column('option_id', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['response_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'question_id', name='uq_answer_per_question')
    )
    with op.batch_alter_table('answers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_answers_session_id'), ['session_id'], unique=False)
        batch_op.create_index('ix_answers_session_question', ['session_id', 'question_id'], unique=False)

    op.create_table('cohort_assignments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('cohort_id', sa.String(length=256), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('level_label', sa.String(length=128), nullable=False),
    sa.Column('attributes_used', sa.JSON(), nullable=False),
    sa.Column('fallback_path', sa.JSON(), nullable=False),
    sa.Column('effective_n', sa.Integer(), nullable=False),
    sa.Column('cohort_version', sa.String(length=20), nullable=False),
    sa.Column('privacy_suppressed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['response_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cohort_assignments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cohort_assignments_session_id'), ['session_id'], unique=True)

    op.create_table('dimension_scores',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('dimension', sa.String(length=64), nullable=False),
    sa.Column('raw_score', sa.Float(), nullable=False),
    sa.Column('normalized_score', sa.Float(), nullable=False),
    sa.Column('max_possible', sa.Float(), nullable=False),
    sa.Column('scoring_version', sa.String(length=20), nullable=False),
    sa.Column('blocker_types', sa.JSON(), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['response_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'dimension', name='uq_score_per_dimension')
    )
    with op.batch_alter_table('dimension_scores', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dimension_scores_session_id'), ['session_id'], unique=False)

    op.create_table('operator_results',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('snapshot_id', sa.String(length=36), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.Column('questionnaire_version', sa.String(length=20), nullable=False),
    sa.Column('scoring_version', sa.String(length=20), nullable=False),
    sa.Column('cohort_version', sa.String(length=20), nullable=False),
    sa.Column('rebalancing_version', sa.String(length=20), nullable=False),
    sa.Column('report_json', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['response_sessions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['snapshot_id'], ['benchmark_snapshots.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('operator_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_operator_results_session_id'), ['session_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('operator_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_operator_results_session_id'))

    op.drop_table('operator_results')
    with op.batch_alter_table('dimension_scores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dimension_scores_session_id'))

    op.drop_table('dimension_scores')
    with op.batch_alter_table('cohort_assignments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cohort_assignments_session_id'))

    op.drop_table('cohort_assignments')
    with op.batch_alter_table('answers', schema=None) as batch_op:
        batch_op.drop_index('ix_answers_session_question')
        batch_op.drop_index(batch_op.f('ix_answers_session_id'))

    op.drop_table('answers')
    op.drop_table('aggregate_metrics')
    with op.batch_alter_table('response_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_response_sessions_idempotency_key'))

    op.drop_table('response_sessions')
    with op.batch_alter_table('contact_store', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contact_store_response_id_hash'))

    op.drop_table('contact_store')
    op.drop_table('benchmark_snapshots')
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_events_occurred_at'))
        batch_op.drop_index(batch_op.f('ix_audit_events_event_type'))

    op.drop_table('audit_events')
    # ### end Alembic commands ###
